name: Build JSON Schemas

on:
  pull_request:
    types: [ closed ] # Trigger when a pull request is closed
    branches:
      - main # Only trigger for PRs targeting the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    # Only run on merged PRs or manual dispatch
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x # Use the latest stable Deno version or specify one

      - name: Generate JSON Schemas
        run: deno run --allow-read --allow-write --allow-env scripts/generate-json-schema.ts
        env:
          GITHUB_REPO_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update generated JSON schemas"
          file_pattern: "*.json" # Commit only JSON files in the root
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> 
