name: Deno CI

on:
  push:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Use latest version v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.2.9 # Use specific version 2.2.9

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Run tests and collect coverage
        # Ensure necessary permissions are granted for your tests
        # Replace --allow-all with specific permissions if possible
        run: deno test --allow-all --coverage=cov/

      - name: Generate coverage report
        run: |
          mkdir -p coverage # Ensure coverage directory exists
          deno coverage --lcov cov/ > coverage/cov.lcov

      - name: Type check
        run: deno check src/mod.ts

      - name: Lint documentation
        run: deno doc --lint src/mod.ts

      - name: Test documentation examples
        # Ensure necessary permissions are granted for your doc tests
        # Replace --allow-all with specific permissions if possible
        run: deno test --doc --allow-all 
