name: Create Version PR # Renamed workflow

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-version-branch-and-pr: # Renamed job
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to checkout, commit, push branch
      pull-requests: write # Needed to create a pull request
    # Removed outputs as tag is not created here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Run Tests
        run: deno test

      - name: Determine Version
        id: version
        run: |
          git fetch --tags --force # Ensure we have latest tags
          LATEST_TAG=$(git tag --sort=-v:refname | grep '^v[0-9]\+\.[0-9]\+\.[0-9]\+$' | head -n1)

          # Check if a tag was found, otherwise default
          if [[ -z "$LATEST_TAG" ]]; then
            echo "No valid vX.Y.Z tag found, defaulting to v0.0.0"
            LATEST_TAG="v0.0.0"
          else
            echo "Latest tag found: $LATEST_TAG"
          fi

          # Strip 'v' prefix
          VERSION_STRING="${LATEST_TAG#v}"

          # Split into parts using cut
          MAJOR=$(echo "$VERSION_STRING" | cut -d. -f1)
          MINOR=$(echo "$VERSION_STRING" | cut -d. -f2)
          PATCH=$(echo "$VERSION_STRING" | cut -d. -f3)

          # Validate parts are numbers (basic check)
          if ! [[ "$MAJOR" =~ ^[0-9]+$ && "$MINOR" =~ ^[0-9]+$ && "$PATCH" =~ ^[0-9]+$ ]]; then
            echo "Error: Parsed version parts are not valid numbers: MAJOR='$MAJOR', MINOR='$MINOR', PATCH='$PATCH'"
            exit 1
          fi

          # Calculate new patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_TAG="v${MAJOR}.${MINOR}.${NEW_PATCH}"

          echo "Determined new tag: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Update Version, Create Branch, Commit, Push, and Create PR
        env:
          NEW_TAG_VAR: ${{ steps.version.outputs.new_tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use default token for PR creation
        run: |
          echo "Updating deno.json to version $NEW_TAG_VAR"
          VERSION_NUMBER="${NEW_TAG_VAR#v}"
          jq --arg ver "$VERSION_NUMBER" '.version = $ver' deno.json > tmp.$$.json && mv tmp.$$.json deno.json
          echo "deno.json content after update:"
          cat deno.json

          echo "Configuring git user"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="chore/version-${NEW_TAG_VAR}"
          echo "Creating and checking out new branch: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME

          echo "Adding and committing deno.json"
          git add deno.json
          git commit -m "chore: Bump version to $NEW_TAG_VAR"

          # Removed tag creation

          echo "Pushing branch $BRANCH_NAME"
          # Push only the new branch
          git push origin $BRANCH_NAME

          echo "Creating Pull Request"
          gh pr create \\
            --base main \\
            --head $BRANCH_NAME \\
            --title "chore: Prepare release $NEW_TAG_VAR" \\
            --body "Automated PR to bump version to $NEW_TAG_VAR and update deno.json. Please review and merge to trigger release."

# Removed publish-package and create-github-release jobs from this workflow
# They will be moved to a separate workflow triggered by tag pushes.
# ... existing code ...
# This represents the end of the file
