name: Publish on Release

on:
  release:
    types: [published] # Trigger only when a release is published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed for JSR OIDC authentication
      packages: write # Needed to publish to GitHub Packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        # No with: deno-version needed, defaults to latest stable

      - name: Run JSR Publish
        run: deno task publish
