name: Publish Package and Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.2.3
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Needed to create GitHub releases
  id-token: write # Needed for OIDC authentication with JSR

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          # Check out the specific tag that triggered the workflow
          ref: ${{ github.ref }}

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        # No need to specify deno-version here, v1.x is the default
        # and it's best to use the version the project was tagged with,
        # which setup-deno handles implicitly when checking out the tag.

      - name: Run Tests
        run: deno test

      - name: Publish to JSR
        run: npx jsr publish

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Extract version from tag (e.g., v1.2.3 -> 1.2.3)
          VERSION="${{ github.ref_name }}"
          echo "Creating release for tag $VERSION"
          gh release create "$VERSION" \
             --generate-notes \
             --title "Release $VERSION"
