name: Publish Dry Runs on Release

on:
  release:
    types: [published] # Trigger only when a release is published

jobs:
  publish-dry-runs:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the repository
      id-token: write # Needed for JSR OIDC authentication
      packages: write # Needed to publish to GitHub Packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        # No with: deno-version needed, defaults to latest stable

      - name: Run JSR Publish Dry Run
        run: deno task publish-dry-run

      - name: Build npm package
        run: deno run --allow-read --allow-write --allow-env --allow-net scripts/build_npm.ts
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Publish to GitHub Packages (Dry Run)
        working-directory: ./npm
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
